controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
index:
    path: /index
    controller: App\Controller\IndexController::index
cart:
    path: /cart
    controller: App\Controller\CartController::index
cart_add:
    path: /add/{id}
    controller: App\Controller\CartController::add
cart_remove:
    path: /remove/{id}
    controller: App\Controller\CartController::remove